### ISSUE TITLE
Do not process partis non-"best" partitions by default

### ISSUE THREAD

**Issue by eharkins** [matsengrp/cft#273]
@lauradoepker said she would no longer like to have partitions other that the best partition be processed by default; since this seems like it was a feature added for her projects, it seems like we can in fact just process the best partition now by default. Hopefully this will simplify the SConstruct code (although having an option to do this if desired may mean adding in some logic for that) and reduce build time.

**Comment by metasoarous** [comment]
By default, we only process the "best" partition except in one case: If there aren't enough sequences in the "best" partition to actually build a tree, we look at later partitions in the partis merging process, until we find one that has enough sequences.

So, first step, let's double check whether this is something @lauradoepker wants to keep or not. Second step, let's ask ourselves whether this is something we want to keep for other reasons.

**Comment by lauradoepker** [comment]
Yes this is great @metasoarous

Duncan, this is exactly what is ideal - only caring about best in most cases except if best+n gives us sequences when best doesn’t. @psathyrella

Can you alter partis to just default display only best partition? Or would you rather cut best+n out completely. If so, I can side with cutting it out completely since we’ve gotten nice families for our most important Abs.

**Comment by psathyrella** [comment]
@lauradoepker do you mean in partis view-output ascii output? There's an option to only display the best partition, --only-print-best-partition. The reason that this isn't the default is that in cases such as this, where we/the user has[ve] specifically asked it to make more partitions and annotate them, I think it would be confusing to hide them by default when running view-output. If you're meaning in some other display? It's certainly super easy to display whatever, but you'd have to point me to what you're looking at.

**Comment by eharkins** [comment]
> By default, we only process the "best" partition except in one case: If there aren't enough sequences in the "best" partition to actually build a tree, we look at later partitions in the partis merging process, until we find one that has enough sequences.

@metasoarous https://github.com/matsengrp/cft/blob/master/SConstruct#L383 would lead me to believe that we process other partitions regardless of the size of the best partition.

@lauradoepker it seems like there are two things being discussed here:
1. CFT processing / not the partitions listed in the `other-partitions` key in partis info.yaml files
2. How partitions are displayed in partis' view-output command. 

-------
1. It seems like if `other-partitions` key exists it's because we care about those partitions, so I think cft should process those by default
2. Does Duncan's comment clarify?

**Comment by psathyrella** [comment]
just to be clear, the 'other-partitions' key in info.yaml and the non-best partitions are entirely separate things.

The former is when we re-run partitioning with a different set of options -- maybe use a different seed for choosing a random subset of sequences -- we give that rerun an additional str label (like `-isub-0`) and record it in `other-partitions`.

non-best-partitions, on the other hand, is a characteristic of all partition output, and just means that every partition output contains several partitions in addition to the best one.

**Comment by eharkins** [comment]
Ah thanks @psathyrella I had a feeling I was not getting something here.

Still a little confused by @metasoarous comment since https://github.com/matsengrp/cft/blob/master/SConstruct#L387 doesn't seem to stop when the seed cluster in the best partition has a sufficient size.

**Comment by metasoarous** [comment]
Ah; I stand corrected! What I said _used_ to be the case, but it looks like we commented out the code here at some point:

https://github.com/matsengrp/cft/blob/master/SConstruct#L398

So yeah, we do always process later partition steps now. I think Duncan suggested this should be fine, because folks probably don't typically run with that setting. But I guess if we only care about them when there's sequences getting left out, we shouldn't waste the compute power in general. So fine I think to add an scons arg something like `--process-all-partis-partition-steps` (or something more concise) which toggles the behavior, the default being to only process the best (unless it's not bigger than 50, as presently commented out).

Please let me know if that makes sense.

**Comment by psathyrella** [comment]
People will almost never use the options that we're using to force partitioning to continue until at least one cluster is bigger than 50 sequences, but partition output always has a number of partitions surrounding the best partition. Typically, these non-best partitions are mostly before (i.e. have more clusters than) the best partition. So the uncommon option that we're using increases the number of non-best partitions.

But in general yes, I think it would be better to only process the best one by default.

**Comment by eharkins** [comment]
Ok, I can add --process-all-partis-partition-steps to be able to process *all* partitions (not starting at `i_best`) and make default best only. Thanks @metasoarous @psathyrella !

**Comment by metasoarous** [comment]
@eharkins I don't think we ever want to not start at `i_best`, unless I'm mistaken (please correct me if I'm wrong @psathyrella).

@psathyrella Does _your_ processing of later partition steps stop once you reach one of size 50 or greater?

**Comment by psathyrella** [comment]
yeah you're wrong ;-) there's no reason in principle why someone wouldn't be as interested in more-split as more-merged partitions. Laura just happens to have only so far been interested in more-merged ones.

I'm not sure what processing you're referring to? When the argument --min-largest-cluster-size is set, clustering stops as soon as any cluster gets larger than that size.

**Comment by metasoarous** [comment]
> there's no reason in principle why someone wouldn't be as interested in more-split as more-merged partitions.

Oh! Great then :-) Sorry for missing that. Carry on!

> When the argument --min-largest-cluster-size is set, clustering stops as soon as any cluster gets larger than that size.

Got it; Thanks for clarifying this as well.

**Comment by eharkins** [comment]
@metasoarous is there a reason why we shouldn't add this option for unseeded partitions as well (https://github.com/matsengrp/cft/blob/master/SConstruct#L859)?

**Comment by metasoarous** [comment]
Yes. potentially; because there could be lots of them, and someone might not be expecting that.

In the past @lauradoepker was only interested in these "other partitions" for seeded clusters. In most cases, the top 50 or whatever clusters you're looking at are going to be big enough that you won't need to be looking at the other partitions. However, as @psathyrella has pointed out, we shouldn't necessarily be limiting things based on what Laura has wanted in the past.

Still, there's concern on my end that someone who didn't realize what they were getting themselves into (maybe who just wanted to look at more detailed partitioning for a couple of seeds) would end up with a massive build time unnecessarily. It's possible that the flow of how they run things feeding into this would make this a non-issue however. I'm guessing that since folks would generally be running seeded data separately from unseeded data, and since having the "extra partitions" in the output file is fully opt-in on partis' part, folks would have had to ask for extra partitions for both seeded and unseeded data for this to even be an issue, and in that case, it would probably have been intentional to look at the other partitions for the unseeded data. Am I making sense @psathyrella?

**Comment by eharkins** [comment]
Just want to make the [distinction here between `other-partitions` and non-best partitions](https://github.com/matsengrp/cft/issues/273#issuecomment-502886779); I assume you mean the latter here @metasoarous, since that's what this issue is covering

**Comment by psathyrella** [comment]
Yeah I think it makes sense to have this option for both seeded and unseeded. As long as the option names are pretty clear on what seeded vs unseeded and process-all-partitions vs not are I don't think people will run it by accident.

**Comment by eharkins** [comment]
https://github.com/matsengrp/cft/pull/289
