### ISSUE TITLE
Make it very obvious when sequences have an indel

### ISSUE THREAD

**Issue by matsen** [matsengrp/cft#282]
This should be true in Olmsted.

@lauradoepker, are there other ways in which you look at the data?

**Comment by eharkins** [comment]
I can open an Olmsted issue for this, but we also discussed CFT raising an exception if a seed sequence have an indel and one is not running with the option outlined in #281. I will probably convert this issue for that specific goal.

**Comment by metasoarous** [comment]
What about adding some combination of:
* color by options (for the big scatterplot or for the tree/aln labels)?
* add a column to the table for `has_indels?`

**Comment by lauradoepker** [comment]
@matsen I have never used Olmsted.  I haven't used CFT since the early days.  I usually go straight from partis to ecgtheow or linearham and, because of this, it would be helpful to render the ML tree during EC/LH so I can sanity check the family, but this doesn't flag indel events.  Though perhaps I should sanity check using Olmsted instead?  In EC, I always look at the pruned FastTree file, but then there isn't another single tree image file made with only the pruned sequences.

I like @eharkins 's suggesting to actually throw an alert/error if trying to run a lineage analysis (EC/LH) on a family that has indels... this is the most foolproof way to make sure the user is on board before proceeding.

**Comment by matsen** [comment]
@lauradoepker Well, we'd love to have you using Olmsted :)

This is getting a little off topic, but if there's a missing feature in Olmsted there let us know!

**Comment by psathyrella** [comment]
I know I'm kind of annoying on this, but I really think that no matter how many alerts we put for different things (not that we shouldn't have an alert for this), looking at the annotation/alignment in something, whether partis or olmsted or whatever, is always going to need to be the first step for any family we're going to do something with. There's just been too many different ways that things have looked weird that we won't otherwise notice, and will waste tons of time if not accounted for.

**Comment by metasoarous** [comment]
@lauradoepker - Yes, we need to get you using Olmsted! @eharkins has been running data and will be setting up a local deployment for you soon.

And yes, please let us know if there's something we could add to Olmsted which might make it more useful to you, especially as far as the kind of Q/A review @psathyrella is talking about.

**Comment by eharkins** [comment]
@lauradoepker @matsen would we still like to make some UI feature in olmsted that highlights indels? I have added https://github.com/matsengrp/cft/issues/281 which means indels in the seed should raise an exception (unless you explicitly tell it to ignore them) in anything that calls https://github.com/matsengrp/cft/blob/master/bin/process_partis.py (eg cft, ecgtheow, but not LH). 

If so I will open such an issue in the olmsted repo.
